name: Build and runtime

on:
  push:
    branches: ["neoforge"]
  pull_request:
    branches: ["neoforge"]

permissions:
  contents: read

jobs:
  runtime:
    uses: bertie-mc/bertie-ci/.github/workflows/neoforge-mod.yml@v2
    with:
      sides: client
