name: Build and test

on:
  push:
    branches: ["neoforge"]
  pull_request:
    branches: ["neoforge"]

permissions:
  contents: read

jobs:
  build:
    uses: bertie-mc/bertie/.github/workflows/build-mod.yml@bertie-ci/v5.0.0
    with:
      component: nebs

  unit-test:
    uses: bertie-mc/bertie/.github/workflows/unit-test.yml@bertie-ci/v5.0.0
    with:
      component: nebs

  client-test:
    needs: build
    uses: bertie-mc/bertie/.github/workflows/client-test.yml@bertie-ci/v5.0.0
    with:
      component: nebs
      artifact-name: ${{ needs.build.outputs.artifact-name }}
