name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  build:
    uses: bertie-mc/bertie/.github/workflows/build-mod.yml@bertie-ci/v5.0.0
    with:
      component: nebs

  publish:
    needs: build
    uses: bertie-mc/bertie/.github/workflows/github-release.yml@bertie-ci/v5.0.0
    with:
      artifact-name: ${{ needs.build.outputs.artifact-name }}
      name: Neko's Enchanted Books ${{ github.ref_name }}
      body: Release of Neko's Enchanted Books ${{ github.ref_name }}.
